# wrangler-ice-ranch.toml - Ice Ranch scraper worker with Durable Objects
name = "rink-scraper-ice-ranch"
main = "workers/scrapers/ice-ranch.ts"
compatibility_date = "2024-10-21"

# KV namespace for storing rink data (same as data API)
[[kv_namespaces]]
binding = "RINK_DATA"
id = "a38bbfdc3fe74d69a0ef39550960eca3"
preview_id = "81d647252e8e4e4caa0047a42ae2bd29"

# Durable Object for scheduling
[[durable_objects.bindings]]
name = "ICE_RANCH_SCHEDULER"
class_name = "IceRanchScheduler"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "IceRanchScheduler" ]

# Cron triggers to wake up and schedule alarms
[triggers]
crons = [
  "0 */12 * * *" # Every 12 hours - worker will schedule alarm with splay
]
