# wrangler-foothills-edge.toml - Foothills Edge scraper worker
name = "rink-scraper-foothills-edge"
main = "workers/scrapers/foothills-edge.ts"
compatibility_date = "2024-10-21"

[[kv_namespaces]]
binding = "RINK_DATA"
id = "a38bbfdc3fe74d69a0ef39550960eca3"
preview_id = "81d647252e8e4e4caa0047a42ae2bd29"

[[durable_objects.bindings]]
name = "FOOTHILLS_EDGE_SCHEDULER"
class_name = "FoothillsEdgeScheduler"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "FoothillsEdgeScheduler" ]

[triggers]
crons = [
  "0 */12 * * *"
]

