# wrangler-big-bear.toml - Big Bear scraper worker
name = "rink-scraper-big-bear"
main = "workers/scrapers/big-bear.ts"
compatibility_date = "2024-10-21"

[[kv_namespaces]]
binding = "RINK_DATA"
id = "a38bbfdc3fe74d69a0ef39550960eca3"
preview_id = "81d647252e8e4e4caa0047a42ae2bd29"

[[durable_objects.bindings]]
name = "BIG_BEAR_SCHEDULER"
class_name = "BigBearScheduler"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BigBearScheduler"]

[vars]
SCRAPER_SPLAY_MINUTES = "350"

# Cron triggers removed - now managed by centralized scheduler
# The scheduler will trigger this worker via GET /schedule

