# wrangler-du-ritchie.toml - DU Ritchie scraper worker
name = "rink-scraper-du-ritchie"
main = "workers/scrapers/du-ritchie.ts"
compatibility_date = "2024-10-21"

[[kv_namespaces]]
binding = "RINK_DATA"
id = "a38bbfdc3fe74d69a0ef39550960eca3"
preview_id = "81d647252e8e4e4caa0047a42ae2bd29"

[triggers]
crons = [
  "0 */12 * * *"
]

