name: Android Build

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'android/**'
      - 'capacitor.config.ts'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/android-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'android/**'
      - 'capacitor.config.ts'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/android-build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: npm ci
      
    - name: Build web app
      run: npm run build
      
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Generate debug keystore
      run: |
        keytool -genkeypair \
          -keystore android/app/debug.keystore \
          -alias androiddebugkey \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass android \
          -keypass android \
          -dname "CN=Android Debug, O=Android, C=US"
      
    - name: Build Android Debug APK
      run: |
        cd android
        ./gradlew assembleProdDebug
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: android/app/build/outputs/apk/prod/debug/app-prod-debug.apk
        
    - name: Build Android Release APK (if main branch)
      if: github.ref == 'refs/heads/main'
      run: |
        cd android
        ./gradlew assembleProdRelease
        
    - name: Upload Release APK
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: android/app/build/outputs/apk/prod/release/app-prod-release-unsigned.apk
        
    - name: Build Android App Bundle (if main branch)
      if: github.ref == 'refs/heads/main'
      run: |
        cd android
        ./gradlew bundleProdRelease
        
    - name: Upload App Bundle
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: app-bundle
        path: android/app/build/outputs/bundle/prod/release/app-prod-release.aab

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write
    
    steps:
    - name: Download Release APK
      uses: actions/download-artifact@v4
      with:
        name: release-apk
        path: ./artifacts/
        
    - name: Download Debug APK
      uses: actions/download-artifact@v4
      with:
        name: debug-apk
        path: ./artifacts/
        
    - name: Download App Bundle
      uses: actions/download-artifact@v4
      with:
        name: app-bundle
        path: ./artifacts/
        
    - name: Generate release tag
      id: tag
      run: |
        TAG="android-build-$(date +%Y%m%d-%H%M%S)"
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "Generated tag: $TAG"
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        name: "Android Build ${{ steps.tag.outputs.tag }}"
        body: |
          Android build artifacts from commit ${{ github.sha }}
          
          **Files included:**
          - `app-prod-release-unsigned.apk` - Production release APK (unsigned)
          - `app-prod-debug.apk` - Production debug APK 
          - `app-prod-release.aab` - Production release App Bundle
          
          **Installation:**
          - Download the APK file
          - Enable "Install from unknown sources" in Android settings
          - Install the APK file
        files: |
          ./artifacts/app-prod-release-unsigned.apk
          ./artifacts/app-prod-debug.apk
          ./artifacts/app-prod-release.aab
        prerelease: true
        generate_release_notes: true