name: Scheduled Tests

on:
  schedule:
    # Run daily at 0:00 AM UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  scraper-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm install --frozen-lockfile

    - name: Test scrapers
      run: |
        echo "🔍 Testing all scrapers to detect website changes..."
        
        # Test each scraper individually (only if test file exists)
        [ -f workers/scrapers/apex-ice.test.ts ] && npx vitest run workers/scrapers/apex-ice.test.ts
        [ -f workers/scrapers/big-bear.test.ts ] && npx vitest run workers/scrapers/big-bear.test.ts || true
        [ -f workers/scrapers/du-ritchie.test.ts ] && npx vitest run workers/scrapers/du-ritchie.test.ts || true
        [ -f workers/scrapers/foothills-edge.test.ts ] && npx vitest run workers/scrapers/foothills-edge.test.ts || true
        [ -f workers/scrapers/ice-ranch.test.ts ] && npx vitest run workers/scrapers/ice-ranch.test.ts || true
        [ -f workers/scrapers/ssprd.test.ts ] && npx vitest run workers/scrapers/ssprd.test.ts || true
        
        echo "✅ Scraper tests completed"

    - name: Notify if tests failed
      if: failure()
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const issueTitle = 'Scheduled Scraper Tests Failed';
          const issueBody = 'The daily scraper tests have failed. This may indicate that one or more rink websites have changed their structure.\n\nSee the workflow run for details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
          
          // Check if issue already exists
          const issues = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            labels: ['scraper-failure']
          });
          
          // Only create a new issue if one doesn't already exist
          if (issues.data.length === 0) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['scraper-failure', 'automated']
            });
          }
