name: Scrape Foothills Ice Arena (Edge)

on:
  schedule:
    # Run at 3:00 AM and 3:00 PM UTC (8:00 PM and 8:00 AM Mountain Time)
    - cron: '0 4,16 * * *'
  workflow_dispatch: # Allow manual triggering
    inputs:
      with_delay:
        description: 'Pause randomly before scraping?'
        required: false
        default: 'false'

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    # only inject a random sleep when this was kicked off by the schedule,
    # so manual runs skip immediately to scraping
    - name: Random delay for schedule runs
      if: |
        github.event_name == 'schedule' ||
        (github.event_name == 'workflow_dispatch' && github.event.inputs.with_delay == 'true')
      run: |
        delay=$((RANDOM % 3600))
        echo "Adding ${delay}s delay for load distribution…"
        sleep $delay

    - name: Scrape Foothills Ice Arena (Edge)
      run: bun run scrape:foothills-edge

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🏫 Update Foothills Ice Arena (Edge) schedule data $(date -u '+%Y-%m-%d %H:%M UTC')"
          git push
        fi

    - name: Show scraping status
      if: always()
      run: bun run scrape --status

