name: Scrape DU Ritchie

on:
  schedule:
    # Run at 3:00 AM and 3:00 PM UTC (8:00 PM and 8:00 AM Mountain Time)
    - cron: '0 3,15 * * *'
  workflow_dispatch: # Allow manual triggering
    inputs:
      with_delay:
        description: 'Pause randomly before scraping?'
        required: false
        default: 'false'

# Add permissions to allow the workflow to push changes
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: |
        export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
        export PUPPETEER_SKIP_DOWNLOAD=true
        bun install --frozen-lockfile --production

    # only inject a random sleep when this was kicked off by the schedule,
    # so manual runs skip immediately to scraping
    - name: Random delay for schedule runs
      if: |
        github.event_name == 'schedule' ||
        (github.event_name == 'workflow_dispatch' && github.event.inputs.with_delay == 'true')
      run: |
        delay=$((RANDOM % 3600))
        echo "Adding ${delay}s delay for load distribution…"
        sleep $delay

    - name: Scrape DU Ritchie Center
      run: bun run scrape:du-ritchie

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/data/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          # Stash the staged changes
          git stash push -m "temp stash for sync" --include-untracked
          
          # Pull latest changes
          git pull --ff-only || {
            echo "Cannot fast-forward, trying rebase approach"
            git pull --rebase
          }
          
          # Re-apply our changes
          git stash pop
          
          # Re-stage the files (stash pop unstages them)
          git add public/data/
          
          # Commit and push
          git commit -m "🏫 Update DU Ritchie schedule data $(date -u '+%Y-%m-%d %H:%M UTC')"
          git push
        fi

    - name: Show scraping status
      if: always()
      run: bun run scrape --status

