name: Run Tests

on:
  push:
    branches: [ main, fixes ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Run tests
      run: bun run test --run
      
    - name: Run build test
      run: bun run build

  timezone-tests:
    runs-on: ubuntu-latest
    name: Test timezone conversions
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Run timezone-specific tests
      run: |
        echo "Testing timezone conversions..."
        bun test workers/shared/timezone-utils.test.ts
        bun test workers/scrapers/apex-ice.test.ts
        echo "✅ Timezone tests passed"

    - name: Verify no midnight time bugs
      run: |
        echo "Checking for timezone conversion issues..."
        # This test ensures our fix prevents midnight display times
        if bun test workers/scrapers/apex-ice.test.ts --reporter=verbose | grep -q "prevents midnight time display bug.*pass"; then
          echo "✅ Midnight time bug prevention test passed"
        else
          echo "❌ Midnight time bug prevention test failed"
          exit 1
        fi